### PR TITLE
Template updates

### PR DESCRIPTION
**Pull request by michalbundyra**
- added slack and forum links (footer)
- removed IRC link
- updated all links to https
- changed logo to SVG image
- updated styles to match current styles from `zf-mkdocs-theme` (generated there without prism)
- updated to latest version of Bootstrap (3.3.7) and FontAwesome (4.7.0) - served from CDN
- removed all unused resources: js, css, fonts

### CODE REVIEW

**Comment by michalbundyra** [comment]
@froschdesign can you have a look, please?

**Comment by froschdesign** [comment]
@webimpress 
I would prefer to use MkDocs for this repository too. No duplicates of templates and all other files like the logo.
I think it should work.

**Comment by michalbundyra** [comment]
@froschdesign 
> I would prefer to use MkDocs for this repository too.

Yeah, me too, but how to do that? There is no `gh-pages` branch so we need to have here final html file.

**Comment by froschdesign** [comment]
@weierophinney must add this branch.

**Comment by michalbundyra** [comment]
@froschdesign I can see couple issues with it:
- homepage is different - we don't have "components" and "search" buttons on top nav (and in template is not possible to disable them)
- on homepage we are not using any JS and we don't need prismjs, so compiled css can be lower here
- in other components we are using files from this repository - `mkdocs/js/search.js` and `mkdocs/js/require.js`, if we create `gh-pages` branch then we have to move these files there as well, so we can't use normal build process (from theme repo).

In general it will be possible but still requires some changes in template, creating `gh-pages` branch etc. I would stick with this solution for now, till you push the new template 😍

**Comment by froschdesign** [comment]
@webimpress 
All these points are correct and I think we should merge your changes the fix the _current_ problems. We can simplify this repository with the next steps.

/cc @weierophinney

**Review by froschdesign — APPROVED** [review]

**Comment by weierophinney** [comment]
Thanks, @webimpress; looks good!

**Pull request merged**
